[package]
name = "tac_70"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["crates/*"]

[dependencies]
tac_core = { path= "crates/tac_core" }
tac_cart = { path= "crates/tac_cart" }