[package]
name = "tac_runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlua = "0.19.1"
tac_core = {path="../tac_core"}
rgb = "0.8.32"
