[package]
name = "tac_runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mlua = { version = "0.8.1", features = ["lua53"] }
tac_core = {path="../tac_core"}