[package]
name = "tac_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
rgb = "0.8.32"
itertools = "0.10.3"
tac_cart = {path="../tac_cart"}