[package]
name = "tac_cart"
description = "TIC-80/TAC-70 cart loader"
authors = ["DMClVG"]
version = "0.1.0"
edition = "2021"
keywords = ["tac"]
repository = "https://github.com/DMClVG/TAC-70"
license = "MIT"

[dependencies]
binread = "2.2.0"
binwrite = "0.2.1"
modular-bitfield = "0.11.2"